delete from ligne; 
delete from arret; 
insert into ligne (num_ligne) values('1'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '1', 'Albert 1er'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '2', 'Antigone'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '3', 'Boutonnet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '4', 'Chateau D o'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '5', 'Comedie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '6', 'Corum T1'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '958', 'Du Guesclin'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '7', 'Euromedecine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '8', 'Gare St-roch T1'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '9', 'Halles Paillade'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '10', 'Hauts De Massane'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '11', 'Hop. Lapeyronie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '13', 'Leon Blum'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '14', 'Louis Blanc'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '15', 'Malbosc'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '16', 'Millenaire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '918', 'Mondial 98'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '17', 'Mosson'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '18', 'Moulares'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '19', 'Occitanie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '20', 'Odysseum'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '21', 'Philipp<option>es'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '22', 'Pl. De L europ'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '23', 'Place De France'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '24', 'Port Marianne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '25', 'Rives Du Lez T1'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '26', 'Saint Eloi'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '27', 'Saint Paul'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '1005', 'Stade Mosson'); 
insert into arret (num_ligne, id_arret, nom_arret) values('1', '28', 'Universites'); 
insert into ligne (num_ligne) values('2'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '30', 'Aiguelongue'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '31', 'Aube Rouge'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '32', 'Beaux Arts'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '33', 'Centurions'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '34', 'Ch. De Gaulle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '35', 'Clairval'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '837', 'Comedie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '36', 'Corum T2'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '37', 'Croix D argent'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '838', 'Gare St-roch T1'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '39', 'Georges Pomp<option>ou'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '40', 'Jacou'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '41', 'La Condamine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '42', 'La Galine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '43', 'Lemasson'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '45', 'Mail Des Abbes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '46', 'Mas Drevon'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '47', 'Nd Sablassou'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '48', 'Nouveau St Roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '53', 'Rondelet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '54', 'Sabines'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '55', 'Saint Cleophas'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '56', 'Saint Lazare'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '57', 'St Jean Centre'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '58', 'St Jean Le Sec'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '59', 'Via Domitia'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '60', 'Victoire 2'); 
insert into arret (num_ligne, id_arret, nom_arret) values('2', '61', 'Vil. D angoule'); 
insert into ligne (num_ligne) values('3'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '959', 'Astruc'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '997', 'Boirargues'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '960', 'Celleneuve'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '998', 'Cougourlude'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '999', 'Ecopole'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '1000', 'Etang De L or'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '961', 'Gare St-roch T3'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '962', 'H.du Departement'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '963', 'Hot. Departement'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '964', 'Jules Guesde'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '1001', 'Juvignac'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '1002', 'Lattes Centre'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '965', 'Les Arceaux'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '966', 'Mosson'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '967', 'Moulares'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '968', 'Observatoire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '969', 'Pablo Picasso'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '1003', 'Parc Expo'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '970', 'Pergola'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '1004', 'Perols Centre'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '971', 'Pilory'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '972', 'Place Carnot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '973', 'Plan Cabanes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '974', 'Port Marianne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '975', 'Rives Du Lez T2'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '976', 'Saint-denis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '977', 'Saintdenis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '978', 'Tonnelles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('3', '979', 'Voltaire'); 
insert into ligne (num_ligne) values('4'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '980', 'Albert 1er'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '981', 'Corum T1'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '982', 'Garcia Lorca'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '983', 'Gare St-roch T3'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '984', 'Hotel De Ville'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '985', 'La Rauze'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '986', 'Les Aubes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '987', 'Louis Blanc'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '988', 'Nouveau St Roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '989', 'Observatoire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '990', 'Pl. De L europ'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '991', 'Pompignane'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '992', 'Restanque'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '993', 'Rives Du Lez T1'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '994', 'Rondelet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '995', 'Saint-denis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('4', '996', 'Saint-martin'); 
insert into ligne (num_ligne) values('6'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1006', 'Alco'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1007', 'Ambroise Pare'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '78', 'Anatole France'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1008', 'Antennes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1009', 'Apothicaires'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1010', 'Appel Du 18 Juin'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '81', 'Av. De Toulouse'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '84', 'Berthelot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1011', 'Cevennes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1012', 'Chateau D o'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1013', 'Coll. C. Claudel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1014', 'Doria'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '90', 'Estanove'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1015', 'Euromedecine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '91', 'Font Couverte'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '92', 'G. Janvier'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '93', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '94', 'Georges Brassens'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1016', 'Jean Bart'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1017', 'La Gaillarde'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1018', 'Las Rebes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '99', 'Le Grand M'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1019', 'Louis Ravas'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '102', 'Lycee Clemenceau'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '104', 'Observatoire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1020', 'Occitanie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '105', 'Paladilhe'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '107', 'Pas Du Loup'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '111', 'Peyrou'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1021', 'Pierre Viala'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '112', 'Pitot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '113', 'Place Du 8 Mai'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1022', 'Puech Villa'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '115', 'Ronceray'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '116', 'Rondelet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1023', 'Rte De Ganges'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '118', 'Saint Denis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '120', 'Saint Guilhem'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1024', 'Saint Priest'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1025', 'Sainte Genevieve'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1026', 'Sainte Therese'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '1027', 'Val D aurelle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('6', '121', 'Vega'); 
insert into ligne (num_ligne) values('7'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '122', 'Anatole France'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '123', 'Berthelot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '124', 'Cervantes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '125', 'Chateau D o'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '126', 'Cite Roger'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '128', 'Croix Rosiers'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '129', 'Crx Du Capitaine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '130', 'Doria'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '131', 'Etoile'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '132', 'Figairasse'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '133', 'Font Trouve'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '134', 'Francois Dezeuze'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '135', 'Gardioles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '136', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '137', 'Gouara'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '138', 'Grezes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '139', 'Gustave Eiffel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '140', 'H.du Departement'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '1039', 'Jean Bart'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '142', 'La Martelle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '143', 'La Pile'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '144', 'La Source'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '145', 'Lepic'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '146', 'Les Bouisses'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '147', 'Lycee Clemenceau'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '148', 'Lycee J. Ferry'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '149', 'Lycee J. Monnet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '150', 'Maison Sports'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '151', 'Martelliere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '152', 'Mas De Merle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '154', 'Monsieur Teste'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '155', 'Muriers'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '156', 'Myrtes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '157', 'Observatoire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '158', 'Ormeaux'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '159', 'Peyrou'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '160', 'Pitot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '161', 'Pleiade'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '162', 'Pous De La Sers'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '163', 'Rondelet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '164', 'Saint Denis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '165', 'Saint Guilhem'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '166', 'Saint Jaumes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '167', 'Saint Roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('7', '168', 'Sophie Germain'); 
insert into ligne (num_ligne) values('8'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '169', 'Chambery'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '1050', 'Cite De L arme'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '170', 'Cite Mion'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '171', 'Col. Aiguerelles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '172', 'Frederic Bazille'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '174', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '175', 'Helios'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '176', 'Henri Rene'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '177', 'Jean Mirailhet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '1051', 'Lucullus'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '180', 'Place Carnot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '181', 'Place Strasbourg'); 
insert into arret (num_ligne, id_arret, nom_arret) values('8', '183', 'Soleiado'); 
insert into ligne (num_ligne) values('9'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '184', 'Albert Einstein'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '185', 'Alfred Nobel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '186', 'Andre Malraux'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '922', 'Apollo'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '187', 'Cim. St Etienne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '188', 'Cinq Chalets'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '189', 'Colverts'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '923', 'Dom. Pompignane'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '190', 'Eureka'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '191', 'Evariste Gallois'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '192', 'Fr. Couperin'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '193', 'G. Marconi'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '194', 'Georges Melies'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '195', 'Grammont'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '196', 'Louis Lepine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '197', 'Marie Durand'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '199', 'Paul Painleve'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '924', 'Pierre Laroque'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '200', 'Pinville'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '201', 'Pl. De L europ'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '1140', 'Place De France'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '202', 'Pompignag Semard'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '203', 'Saint Jean'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '204', 'Saint Michel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '1143', 'Saint-michel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '205', 'Samuel Morse'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '206', 'Vieille Poste'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '207', 'Volta Fizeau'); 
insert into arret (num_ligne, id_arret, nom_arret) values('9', '208', 'Zenith'); 
insert into ligne (num_ligne) values('10'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1053', 'A. L. Jussieu'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '210', 'Aiguelongue'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1054', 'Aiguelongue Juss'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1055', 'Alpilles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1057', 'Av. Agriculture'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '211', 'Belvedere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1058', 'Celleneuve'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1059', 'Chantecler'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1060', 'Charles Flahaut'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1061', 'Clinique Rech'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1062', 'Clolus'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1063', 'Coll. C.claudel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1064', 'Doria'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1065', 'Erables'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1066', 'Esperance'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '219', 'Fac De Pharmacie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1067', 'Glycines'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '222', 'Henri Dunant'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1068', 'La Pile'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1069', 'Las Cazes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1070', 'Las Sorbes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1071', 'Louvain'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1072', 'Marie Caizergues'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1073', 'Marie Curie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1074', 'Moulin Gasconnet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1075', 'Nazareth'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1076', 'Paladilhe'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1077', 'Petit Bard'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1078', 'Pierre Rouge'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1079', 'Pioch Boutonnet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1080', 'Renaudel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1081', 'Rene Bougnol'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1082', 'Saint Clement'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '251', 'Saint Eloi'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1083', 'Saint Gabriel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1084', 'Saint Roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '1085', 'Sainte Odile'); 
insert into arret (num_ligne, id_arret, nom_arret) values('10', '257', 'Tonnelles'); 
insert into ligne (num_ligne) values('11'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '262', 'Anatole France'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '263', 'Bagatelle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '264', 'Chasseurs'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '265', 'Cheng-du'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '266', 'Cite Gely'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '267', 'Cite Valette'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '268', 'Claret'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '269', 'College Pagnol'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '271', 'Craponne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '272', 'Figuerolles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '273', 'Gambetta'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '274', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '275', 'Les Bouisses'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '276', 'Les Roses'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '910', 'Observatoire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '1052', 'Palissade'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '277', 'Pas Du Loup'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '278', 'Paul Fajon'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '279', 'Plan Cabanes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '280', 'Renouvier'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '281', 'Rouget De Lisle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('11', '282', 'Saint Denis'); 
insert into ligne (num_ligne) values('12'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '283', 'Bellevue'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '1141', 'Catalpas'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '284', 'Centrayrargues'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '285', 'Coquelicots'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '286', 'Descartes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '287', 'Frederic Peysson'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '289', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '290', 'Henri Rene'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '291', 'Jean Vachet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '293', 'Leon Cordes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '294', 'Marechal Leclerc'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '295', 'Paquerettes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '296', 'Place Carnot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '297', 'Place Strasbourg'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '298', 'Porto'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '299', 'Primeveres'); 
insert into arret (num_ligne, id_arret, nom_arret) values('12', '300', 'Razeteurs'); 
insert into ligne (num_ligne) values('13'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '302', 'Agropolis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '303', 'Campus Agropolis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '304', 'E. Architecture'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '305', 'Ecossais'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '306', 'Eugene Bataillon'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '307', 'Fac De Lettres'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '308', 'Gascogne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '309', 'Henri Dunant'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '310', 'Hortus'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '311', 'Lavalette'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '312', 'Lycee F. Bazille'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '313', 'Maurice Chauvet'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '314', 'Pic St Loup'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '315', 'Plan 4 Seigneurs'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '316', 'Saint Eloi'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '317', 'Universites'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '318', 'Vert Bois'); 
insert into arret (num_ligne, id_arret, nom_arret) values('13', '319', 'Zoo'); 
insert into ligne (num_ligne) values('14'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '321', 'Bd Des Sports'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '322', 'Ernest Renan'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '323', 'Estragon'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '324', 'Foyer Des Aubes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '325', 'Francoise'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '941', 'Garigliano'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '326', 'Jean Mermoz'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '327', 'Leon Blum'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '328', 'Les Aubes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '942', 'Les Lacs'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '330', 'Palombes'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '331', 'Pinsons'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '333', 'Saint Maur'); 
insert into arret (num_ligne, id_arret, nom_arret) values('14', '943', 'Salaison'); 
insert into ligne (num_ligne) values('15'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1086', 'Aiguelongue'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1087', 'Belvedere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1088', 'Bengalis'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1089', 'Bugarel'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1090', 'Castelle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1091', 'Ch. De Gaulle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1092', 'Cheng-du'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1093', 'Cinsaults'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1094', 'Demeter'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1095', 'Ettore Bugatti'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1096', 'Fac De Pharmacie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1097', 'Garosud'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1098', 'Goelands'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1099', 'Henri Dunant'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1100', 'Henri Mares'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1101', 'Jasse De Maurin'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1102', 'Jean Calvin'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1103', 'Lagoya'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1104', 'Le Grand M'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1105', 'Les Bouisses'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1106', 'Les Lacs'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1107', 'Les Pins'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1108', 'Louis Ravas'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1109', 'Lycee J. Ferry'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1110', 'M. Chevalier'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1111', 'Major Flandre'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1112', 'Martelliere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1113', 'Mas De Bagneres'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1114', 'Millenaire'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1116', 'Ormeaux'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1117', 'Parc Lironde'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1118', 'Passerines'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1119', 'Pastourelles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1120', 'Patrice Lumumba'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1121', 'Paul Fajon'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1122', 'Pierre Laroque'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1123', 'Pinville'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1142', 'Place De France'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1124', 'Pompignag Semard'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1125', 'Rieges'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1126', 'Roqueturiere'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1127', 'Rouget De Lisle'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1128', 'Sabines'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1129', 'Saint Cleophas'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1130', 'Saint Eloi'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1131', 'Saint Lazare'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1132', 'Sainte Catherine'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1133', 'Salaison'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1134', 'Sophie Germain'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1135', 'Tam'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '372', 'Tonnelles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1136', 'Tourterelles'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1137', 'Vauguieres'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1138', 'Voie Domitienne'); 
insert into arret (num_ligne, id_arret, nom_arret) values('15', '1139', 'Yves Du Manoir'); 
insert into ligne (num_ligne) values('16'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '382', 'Cite De L arme'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '383', 'Cite Mion'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '388', 'Fr. Fabreges'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '389', 'Frederic Bazille'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '390', 'Garcia Lorca'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '392', 'Gare Saint-roch'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '393', 'Henri Rene'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '394', 'Industrie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '395', 'Iris'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '400', 'Lucullus'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '401', 'Marche Gare'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '402', 'Mas Argelliers'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '403', 'Mas St Pierre'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '409', 'Place Carnot'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '410', 'Place Strasbourg'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '417', 'Saporta'); 
insert into arret (num_ligne, id_arret, nom_arret) values('16', '418', 'Tournezy'); 
insert into ligne (num_ligne) values('19'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1144', 'Carriera'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1145', 'Comte De Nice'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1146', 'Comte Toulouse'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1147', 'Corse'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1148', 'Coubertin'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1149', 'Gemeaux'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1150', 'H.du Departement'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1151', 'Halles Paillade'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1152', 'Hauts De Massane'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1153', 'Jacques Prevert'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1154', 'Lycee De Vinci'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1155', 'Mas De Bellevue'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1156', 'Oxford'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1157', 'Parc Malbosc'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1158', 'Pierre Cardenal'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1159', 'Pl. D italie'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1160', 'Raimbaud orang'); 
insert into arret (num_ligne, id_arret, nom_arret) values('19', '1161', 'Uppsala'); 
